### ISSUE TITLE
Error build android studio 

### ISSUE THREAD

**Issue by JhonShell** [ElijaxApps-org/android-xmrig-miner#11]
hello, I trying to build the project in android studio 3.1.2 but I get this error .

ndk-build = 18b
Error while executing process /root/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /app/.externalNativeBuild/cmake/debug/x86 --target xmrig }

Log complete from android studio :
[completeLog.txt](https://github.com/ElijaxApps-org/android-xmrig-miner/files/2518403/completeLog.txt)

**Comment by bitcoin-hub** [comment]
Did you fix it ? I have the same question.

**Comment by User0856** [comment]
Did anyone fixed this issue? It is still s valid question.

**Comment by copypasteearth** [comment]
im having the same problem, any fix?

**Comment by ElijaxApps** [comment]
Sorry, this miner proyect is dead.

I refer to you to my fork of @shmulatov's VerusMiner9000.
