### ISSUE TITLE
Anyone got 6.10.0 working with the native build?

### ISSUE THREAD

**Issue by RCTORONTO** [ElijaxApps-org/android-xmrig-miner#22]
Anybody else trying to get a newer xmrig to work with this?  I cannot get Android-studio to produce the newer executable.

**Comment by RCTORONTO** [comment]
I get this message after I disabled the missing extra libraries (pthread rt - I will work on these after)   Policy CMP0040 is not set: The target in the TARGET signature of
  add_custom_command() must exist and must be defined in the current
  directory.  Run "cmake --help-policy CMP0040" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  No TARGET 'xmrig' has been created in this directory.
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by sadakura** [comment]
Same here. Any luck to have output for ARM and ARM64 support with 6.1x ?

**Comment by RCTORONTO** [comment]
we are up to 6.12.1 Xmrig, I would actually pay money for assistance setting up my  Android Studio installs with a project that includes support for building Xmrig 6.12.1 and a recent libuv within the app (I'm not entirely clear how Android apps make use of the native c programs - I've been studying this project to try and figure it all out but have been unsuccessful in "upgrading" it to a current version)

**Comment by ElijaxApps** [comment]
Yeah, sorry. This project is almost dead.

I am going to mantain another miner, fork of @shmulatov VerusMiner900, featuring tpruvot's ccminer.

Forget totally about this project. It was made prior randomx fork on Monero. Even If you compile it, you'll only be able to mine CryptoNight's variants.

Sorry for the lack of maintainment; It's been rough times.
